# Generated by Django 5.0.1 on 2024-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.SlugField(default='this_is_a_slug'),
            preserve_default=False,
        ),
    ]
